ToolLoan/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToolLoan.Data.Models;
using ToolLoan.Models;

namespace ToolLoan.Controllers
{
    public class HomeController : ToolLoanController
    {
        public ActionResult Index()
        {
            BooleanHolder thisOne = new BooleanHolder();

            
            if (base.IsAuthenticated)
            {
                thisOne.isAuthenticated = true;
            }

            else
            {
                thisOne.isAuthenticated = false;
            }

            return View("Index", thisOne);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ToolLoan/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToolLoan.Data.DAL;
using ToolLoan.Data.Models;

namespace ToolLoan.Controllers
{
    
    public class ToolsController : ToolLoanController
    {
        private ToolLoanContext db = new ToolLoanContext();
        private readonly IUserDAL userDal;

        public ToolsController(IUserDAL userDal)
            : base(userDal)
        {
            this.userDal = userDal;
        }

        public ToolsController()
            :base()
        {

        }


        // GET: Tools
        public ActionResult Index()
        {
            if (base.IsAuthenticated)
            {
                return View(db.Tools.ToList());
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }
            
        }

        public ActionResult LibrarianIndex()
        {
            if (base.IsAuthenticated)
            {
                return View(db.Tools.ToList());
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }

        }

        // GET: Tools/Details/5
        public ActionResult Details(int? id)
        {
            if (base.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Tool tool = db.Tools.Find(id);
                if (tool == null)
                {
                    return HttpNotFound();
                }
                return View(tool);
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }

        }

        // GET: Tools/Create
        public ActionResult Create()
        {
            if (base.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }
            
        }

        // POST: Tools/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ToolId,Name,ToolCategoryId,TotalStock,Description,quantity")] Tool tool)
        {
            if (base.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Tools.Add(tool);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(tool);
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }

        }

        // GET: Tools/Edit/5
        public ActionResult Edit(int? id)
        {
            if (base.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Tool tool = db.Tools.Find(id);
                if (tool == null)
                {
                    return HttpNotFound();
                }
                return View(tool);
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }

        }

        // POST: Tools/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ToolId,Name,ToolCategoryId,TotalStock,Description,quantity")] Tool tool)
        {
            if (base.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(tool).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(tool);
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }

        }

        // GET: Tools/Delete/5
        public ActionResult Delete(int? id)
        {
            if (base.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Tool tool = db.Tools.Find(id);
                if (tool == null)
                {
                    return HttpNotFound();
                }
                return View(tool);
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }

        }

        // POST: Tools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (base.IsAuthenticated)
            {
                Tool tool = db.Tools.Find(id);
                db.Tools.Remove(tool);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("LogIn", "Account");
            }

        }


        // Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToolLoan/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Home.cshtml";
}
<h2>About Us</h2>

<div class="jumbotron">
    <p>We are dedicated to helping library patrons and librarians have easy access to tool lending.</p>
    @Html.ActionLink("Home", "Index", "Home", null, new { @type = "button", @class = "btn btn-primary btn-lg" })
    
</div>

ToolLoan/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Home.cshtml";
}
<h2>Contact Us</h2>

<div class="jumbotron">
    <address>
        1700 Euclid Ave<br />
        Cleveland, OH<br />
        <abbr title="Phone">P:</abbr>
        216-867-5309
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">TimAndDave@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:lizzi.melone@gmail.com">Lizzi@example.com</a>
    </address>
    @Html.ActionLink("Home", "Index", "Home", null, new { @type = "button", @class = "btn btn-primary btn-lg" })
</div>

ToolLoan/Views/Home/Index.cshtml
@model ToolLoan.Models.BooleanHolder
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Home.cshtml";
}

<div class="jumbotron">
    <h1>Tool Loan</h1>
    <p class="lead">Your premium source of tool loaning technology</p>
    
    @if (Model.isAuthenticated == true)
    {
        @Html.ActionLink("See Available Tools!", "Index", "Tools", null, new { @type = "button", @class = "btn btn-primary btn-big" })
    }

    else
    {
        @Html.ActionLink("Sign Up!", "SignUp", "Account", null, new { @type = "button", @class = "btn btn-primary btn-lg" }) 
    }
</div>